services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: sgcv-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongo:
    image: mongo:6.0
    container_name: sgcv-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
